# Generated by Django 3.2.18 on 2023-03-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('region', models.CharField(choices=[('UK', 'UK'), ('FR', 'FRANCE'), ('IT', 'ITALY'), ('DE', 'Germany'), ('US', 'USA'), ('JP', 'JAPAN'), ('HK', 'HONGKONG'), ('KR', 'KOREA'), ('NL', 'NEDERLAND'), ('ES', 'SPAIN')], default='uk', max_length=20, verbose_name='지역')),
                ('brand', models.CharField(choices=[('DY', 'Dyson')], default='DY', max_length=20, verbose_name='브랜드')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True, verbose_name='링크')),
                ('color', models.CharField(choices=[(None, None), ('Iron', 'Iron'), ('Copper', 'Copper'), ('Fuchsia', 'Fuchsia')], max_length=10, null=True, verbose_name='색깔')),
                ('is_stock', models.BooleanField(default=False, verbose_name='재고여부')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
